Access to data constructor
yesodweb/wai pull request #841
Opened 2021-03-27 14:54 UTC by tkvogt

I want to update
https://github.com/snoyberg/keter/blob/a829d79bcb08c4180c88f38b174028e5e3f76f27/Keter/Types/V10.hs#L127-L129
to the newest version of warp-tls.
So access to certSettings is needed: https://github.com/yesodweb/wai/blob/f59e577f865d017b4726826ac5586bb916cf315b/warp-tls/Network/Wai/Handler/WarpTLS.hs#L96

2021-03-28 18:39 UTC, snoyberg commented
@kazu-yamamoto you good taking this?

2021-03-29 05:17 UTC, kazu-yamamoto commented
@snoyberg If people want to access `CertSettings`, let's export it. But I would like to discuss which module should export it. This is not a strong opinion but I feel that `Internal` is safer.

2021-05-21 03:48 UTC, kazu-yamamoto commented
@snoyberg Which module do you prefer `WarpTLS.Internal` or `WarpTLS`?

2021-05-21 03:58 UTC, snoyberg commented
I trust your opinion, `.Internal` sounds good to me.

2021-06-25 01:57 UTC, kazu-yamamoto commented
@tkvogt Gentle ping. If you are still interested in this issue, please provide `Internal` module.

2021-06-28 03:52 UTC, kazu-yamamoto requested changes

2021-06-28 03:52 UTC, kazu-yamamoto commented on warp-tls/Network/Wai/Handler/WarpTLS.hs
> +    , CertSettings(..)
Let's not export the data constructors.

2021-06-28 03:52 UTC, kazu-yamamoto commented on warp-tls/Network/Wai/Handler/WarpTLS.hs
> +import Network.Wai.Handler.WarpTLS.Internal(CertSettings(..), TLSSettings(..), OnInsecure(..))
Please remove `(..)` from `CertSettings`.

2021-06-30 01:26 UTC, kazu-yamamoto approved these changes
Now LGTM.

2021-06-30 01:27 UTC, kazu-yamamoto commented
Rebased and merged. Thank you for your contribution!
If you wish, I will release a new version.

2021-09-29 00:39 UTC, kazu-yamamoto commented
A new version of warp-tls has been released. Closing.

2021-09-29 00:39 UTC, closed without merging